apiVersion: v1
kind: Pod
metadata:
  name: init-demo
spec: 
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: workdir
  initContainers:
  - name: install
    image: busybox
    command: ["wget", "-O", "/work-dir/index.html", "http://info.cern.ch"]
    volumeMounts:
      - mountPath: "/work-dir"
        name: workdir
  dnsPolicy: Default
  volumes:
  - name: workdir
    emptyDir: {}